MODULE_TYPE = 'MODULE'
COURSEWORK_TYPE = 'COURSEWORK'
PROJECT_TYPE = 'PROJECT'

MODULE_WEIGHT = 1
COURSEWORK_WEIGHT = 2
PROJECT_WEIGHT = 3

MODULE_COUNT = 70
COURSEWORK_COUNT = 3
PROJECT_COUNT = 3

MODULE_TEXT = 'Module'
COURSEWORK_TEXT = 'Coursework'
PROJECT_TEXT = 'Project'

WORK_TYPES = (
    (MODULE_TYPE, MODULE_WEIGHT, MODULE_COUNT, MODULE_TEXT),
    (COURSEWORK_TYPE, COURSEWORK_WEIGHT, COURSEWORK_COUNT, COURSEWORK_TEXT),
    (PROJECT_TYPE, PROJECT_WEIGHT, PROJECT_COUNT, PROJECT_TEXT)
)

MAIN_MENU_STEP_TYPE = 'MAIN_MENU'
ADDITION_STEP_TYPE = 'ADDITION'
SUBTRACTION_STEP_TYPE = 'SUBTRACTION'
SET_STEP_TYPE = 'SET'
SEE_PROGRESS_STEP_TYPE = 'SEE_PROGRESS'
QUIT_STEP_TYPE = 'QUIT'
BACK_STEP_TYPE = 'BACK'

MAIN_MENU_STEP_TEXT = 'To Main Menu'
ADDITION_STEP_TEXT = 'Add'
SUBTRACTION_STEP_TEXT = 'Subtract'
SET_STEP_TEXT = 'Set'
SEE_PROGRESS_STEP_TEXT = 'See Progress'
QUIT_STEP_TEXT = 'Quit'
BACK_STEP_TEXT = 'Back'

STEP_TYPES = (
    (MAIN_MENU_STEP_TYPE, MAIN_MENU_STEP_TEXT),
    (ADDITION_STEP_TYPE, ADDITION_STEP_TEXT),
    (SUBTRACTION_STEP_TYPE, SUBTRACTION_STEP_TEXT),
    (SET_STEP_TYPE, SET_STEP_TEXT),
    (SEE_PROGRESS_STEP_TYPE, SEE_PROGRESS_STEP_TEXT),
    (QUIT_STEP_TYPE, QUIT_STEP_TEXT),
)

ANSWER = 'ANSWER'

START_DATE = '2022-01-31'
END_DATE = '2022-03-27'

WORK_DIR = 'ProgressCalculator'
